name: Format and test numerical methods

on:
  push:
    branches: 
      - "main"

jobs:
  ruff:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Format & fix
        uses: chartboost/ruff-action@v1
        with:
          args: "check --fix"
  test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python3.12 -m venv .venv
          source .venv/bin/activate
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install pytest
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          python3.12 -m pytest
